// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Tau.KeyVault.Data;

#nullable enable

namespace Tau.KeyVault.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260303000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Tau.KeyVault.Models.AppUser", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");
                b.Property<string>("Username")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("Username").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("Tau.KeyVault.Models.KeyEntry", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");
                b.Property<string>("Key")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.Property<string>("Value")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.Property<string>("Environment")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.Property<bool>("IsJson")
                    .HasColumnType("INTEGER");
                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");
                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("Key", "Environment").IsUnique();
                b.ToTable("KeyEntries");
            });
        }
    }
}
