// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tau.KeyVault.Data;

#nullable disable

namespace Tau.KeyVault.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260910101559_AddKafkaConfigs")]
    partial class AddKafkaConfigs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Tau.KeyVault.Models.AccessAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActorType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("ActorId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Key", "Environment");

                    b.ToTable("AccessAuditLogs");
                });

            modelBuilder.Entity("Tau.KeyVault.Models.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Tau.KeyVault.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tau.KeyVault.Models.EnvironmentApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRotatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Environment");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EnvironmentApiKeys");
                });

            modelBuilder.Entity("Tau.KeyVault.Models.KafkaConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Acks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalConfig")
                        .HasColumnType("TEXT");

                    b.Property<string>("BootstrapServers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompressionType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableIdempotence")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableSslCertificateVerification")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LowercaseEnvironment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessageTimeoutMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OauthBearerClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OauthBearerClientSecret")
                        .HasColumnType("TEXT");

                    b.Property<string>("OauthBearerExtensions")
                        .HasColumnType("TEXT");

                    b.Property<string>("OauthBearerScope")
                        .HasColumnType("TEXT");

                    b.Property<string>("OauthBearerTokenEndpointUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestTimeoutMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SaslKerberosKeytab")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaslKerberosPrincipal")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaslKerberosServiceName")
                        .HasColumnType("TEXT");

                    b.Property<int>("SaslMechanism")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SaslPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaslUsername")
                        .HasColumnType("TEXT");

                    b.Property<int>("SecurityProtocol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SslCaLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("SslCertificateLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("SslKeyLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("SslKeyPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Environment");

                    b.ToTable("KafkaConfigs");
                });

            modelBuilder.Entity("Tau.KeyVault.Models.KeyEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DataType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Environment")
                        .IsUnique();

                    b.ToTable("KeyEntries");
                });

            modelBuilder.Entity("Tau.KeyVault.Models.NatsConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LowercaseEnvironment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Queue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Environment");

                    b.ToTable("NatsConfigs");
                });

            modelBuilder.Entity("Tau.KeyVault.Models.NotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Environment");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("Tau.KeyVault.Models.WebhookConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LowercaseEnvironment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Environment");

                    b.ToTable("WebhookConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
