// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Tau.KeyVault.Data;

#nullable enable

namespace Tau.KeyVault.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304200000_AddNotificationConfigs")]
    partial class AddNotificationConfigs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Tau.KeyVault.Models.AppUser", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");
                b.Property<string>("Username")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("Username").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("Tau.KeyVault.Models.KeyEntry", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");
                b.Property<string>("Key")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.Property<string>("Value")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.Property<string>("Environment")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.Property<int>("DataType")
                    .HasColumnType("INTEGER");
                b.Property<bool>("IsSensitive")
                    .HasColumnType("INTEGER");
                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");
                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("Key", "Environment").IsUnique();
                b.ToTable("KeyEntries");
            });

            modelBuilder.Entity("Tau.KeyVault.Models.NatsConfig", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");
                b.Property<string>("Environment")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.Property<string>("ServerUrl")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.Property<string>("Queue")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.Property<bool>("LowercaseEnvironment")
                    .HasColumnType("INTEGER");
                b.Property<bool>("Enabled")
                    .HasColumnType("INTEGER");
                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("Environment");
                b.ToTable("NatsConfigs");
            });

            modelBuilder.Entity("Tau.KeyVault.Models.WebhookConfig", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");
                b.Property<string>("Environment")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.Property<string>("Url")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.Property<bool>("LowercaseEnvironment")
                    .HasColumnType("INTEGER");
                b.Property<bool>("Enabled")
                    .HasColumnType("INTEGER");
                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("Environment");
                b.ToTable("WebhookConfigs");
            });
        }
    }
}
